# Generated by Django 5.2 on 2025-04-12 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('places_total', models.IntegerField()),
                ('places_reservees', models.IntegerField(default=0)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('image_url', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='a_venir', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('date_generation_qr', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('salle', models.CharField(blank=True, max_length=100)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='api.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('presence', 'Présence'), ('participation', 'Participation'), ('satisfaction', 'Satisfaction')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('url_fichier', models.URLField(blank=True)),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='api.formation')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.formation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.participant')),
            ],
            options={
                'unique_together': {('formation', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent')], default='absent', max_length=10)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='api.participant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='api.seance')),
                ('scanne_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.utilisateur')),
            ],
            options={
                'unique_together': {('seance', 'participant')},
            },
        ),
    ]
